
"""

Author: John Maxi
Date: 2019-09-14
"""

testtables = ['TESTLEADS']

testcolumns = {
'TESTLEADS':"""(
    ID SERIAL NOT NULL,
    SCRAPE_DATE timestamp,
    APPEARED_DATE timestamp,
    CHANGE_TYPE varchar,
    MLS_NUM int,
    ADDRESS varchar,
    CURRENT_PRICE int,
    BEDS int,
    FULL_BATHS int,
    HALF_BATHS int,
    AGE_DESC varchar,
    YR_BLT int,
    SQ_FEET_LV int,
    PROPERTY_TYPE varchar,
    DWELLING_TYPE varchar,
    CITY varchar,
    ZIP int,
    LP_SQ_FT int,
    NEIGHBORHOOD varchar,
    DOM int,
    BOUNDING_STREETS varchar,
    LOT_SIZE varchar,
    LOT_DESCRIPTION varchar,
    ACRES varchar,
    AGE varchar,
    PRIMARY KEY (APPEARED_DATE, ADDRESS)
    )"""
}

tables = ['LEADS']

columns = {
'LEADS':"""(
    ID SERIAL NOT NULL,
    SCRAPE_DATE timestamp,
    APPEARED_DATE timestamp,
    CHANGE_TYPE varchar,
    MLS_NUM int,
    ADDRESS varchar,
    CURRENT_PRICE int,
    BEDS int,
    FULL_BATHS int,
    HALF_BATHS int,
    AGE_DESC varchar,
    YR_BLT int,
    SQ_FEET_LV int,
    PROPERTY_TYPE varchar,
    DWELLING_TYPE varchar,
    CITY varchar,
    ZIP int,
    LP_SQ_FT int,
    NEIGHBORHOOD varchar,
    DOM int,
    BOUNDING_STREETS varchar,
    LOT_SIZE varchar,
    LOT_DESCRIPTION varchar,
    ACRES varchar,
    AGE varchar,
    PRIMARY KEY (APPEARED_DATE, ADDRESS)
    )"""
}

leads_insert = ("""
INSERT INTO LEADS(SCRAPE_DATE, APPEARED_DATE, CHANGE_TYPE, MLS_NUM, ADDRESS, CURRENT_PRICE, BEDS, FULL_BATHS, HALF_BATHS, AGE_DESC, YR_BLT, SQ_FEET_LV,
                  PROPERTY_TYPE, DWELLING_TYPE, CITY, ZIP, LP_SQ_FT, NEIGHBORHOOD, DOM, BOUNDING_STREETS, LOT_SIZE, LOT_DESCRIPTION, ACRES, AGE)
            VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
ON CONFLICT (APPEARED_DATE, ADDRESS)
DO UPDATE SET (SCRAPE_DATE, CHANGE_TYPE, MLS_NUM, CURRENT_PRICE
,BEDS ,FULL_BATHS, HALF_BATHS, AGE_DESC, YR_BLT, SQ_FEET_LV,
PROPERTY_TYPE, DWELLING_TYPE, CITY, ZIP, LP_SQ_FT, NEIGHBORHOOD, DOM, BOUNDING_STREETS, LOT_SIZE, LOT_DESCRIPTION, ACRES, AGE) = (EXCLUDED.SCRAPE_DATE, EXCLUDED.CHANGE_TYPE, EXCLUDED.MLS_NUM, EXCLUDED.CURRENT_PRICE
,EXCLUDED.BEDS ,EXCLUDED.FULL_BATHS, EXCLUDED.HALF_BATHS, EXCLUDED.AGE_DESC, EXCLUDED.YR_BLT, EXCLUDED.SQ_FEET_LV,
EXCLUDED.PROPERTY_TYPE, EXCLUDED.DWELLING_TYPE, EXCLUDED.CITY, EXCLUDED.ZIP, EXCLUDED.LP_SQ_FT, EXCLUDED.NEIGHBORHOOD, EXCLUDED.DOM, EXCLUDED.BOUNDING_STREETS, EXCLUDED.LOT_SIZE, EXCLUDED.LOT_DESCRIPTION, EXCLUDED.ACRES, EXCLUDED.AGE)
""")

leads_list = """\
SELECT
        MLS_NUM
        ,ADDRESS
        ,CURRENT_PRICE
        ,DOM
        ,SCRAPE_DATE
        ,CHANGE_TYPE
        ,AGE_DESC
        ,PROPERTY_TYPE
FROM
        LEADS
WHERE
        CHANGE_TYPE = 'Back On Market'
        OR CHANGE_TYPE = 'Price Decrease'
ORDER BY
        DOM DESC;
"""
